Repository moofarm/ssuckssuck-frontend, pull requests merged in 2024-05, with the labels that each got.

#9 Feat: 헤더 컴포넌트 생성
  src/components/Header.jsx
  src/components/ProfileImage.jsx
  src/components/UserInfo.jsx
Labels: feature, component

#23 Feat: Tab 컴포넌트 UI 생성
  src/components/Tab.jsx
Labels: feature, component

#29 Design: 모달 아래 margin 수정
  package-lock.json
  src/components/modal/Modal.jsx
Labels: component

#33 Feat: 헤더에서 검색 컴포넌트 띄우고 닫기, 방만들기 모달 띄우기
  src/components/Header.jsx
  src/components/SearchContainer.jsx
  src/components/UserInfo.jsx
  src/components/modal/MakeRoomContent.jsx
Labels: feature

#32 Feat: 페이지 레이아웃에 헤더 추가, 각 페이지별 공통 스타일 정의
  src/index.css
  src/layout/PageLayout.jsx
Labels: enhancement

#40 Refactor: Button 컴포넌트 배경색, 텍스트 색 props로 전달 받기
  src/components/Button.jsx
  src/components/Tab.jsx
  src/components/card/CardModal.jsx
  src/components/landing/LandingFirstSection.jsx
  src/components/landing/LandingSecondSection.jsx
  src/components/landing/LandingThirdSection.jsx
  src/components/modal/Modal.jsx
Labels: component, refactor

#43 Feat: 나의미션방 페이지 생성
  src/assets/sad_mussuk.svg
  src/index.css
  src/pages/MyMissionPage.jsx
  src/utils/dummy-datas.js
Labels: enhancement, page
